import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavbarWithDropdown from "@/components/MainNavbar";
import Providers from "@/components/Providers";
import SiteBreadcrumb from "@/components/SiteBreadcrumb";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Cache It For Me',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <Providers>
      <NavbarWithDropdown/>

      <div className="pt-16 px-24 dark:border-gray-700 dark:bg-gray-800 sm:px-4">
        {children}
      </div>
    </Providers>
    </body>
    </html>
  )
}
